---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: debian/stretch64 

suites:
  - name: default
    run_list:
      - recipe[bird::default]
    attributes:
  - name: ipv6
    run_list:
      - recipe[bird::default]
    attributes:
      bird:
        ipv4: false
        ipv6: true
  - name: fullstack
    run_list:
      - recipe[bird::default]
    attributes:
      bird:
        ipv4: true
        ipv6: true
